"""Shared constants for the meta2date filename application."""

from __future__ import annotations

DEFAULT_PATH_DIR = ""
DEFAULT_EXTENSION = "*"
DEFAULT_FILE_NAME = "%Y-%m-%d_%H-%M-%S"

DATE_HELP_TEXT = (
    "%a\tAbbreviated weekday name.\tSun, Mon, ...\n "
    "%A\tFull weekday name.\tSunday, Monday, ...\n "
    "%w\tWeekday as a decimal number.\t0, 1, ..., 6\n "
    "%d\tDay of the month as a zero-padded decimal.\t01, 02, ..., 31 \n "
    "%-d\tDay of the month as a decimal number.\t1, 2, ..., 30\n "
    "%b\tAbbreviated month name.\tJan, Feb, ..., Dec\n "
    "%B\tFull month name.\tJanuary, February, ...\n "
    "%m\tMonth as a zero-padded decimal number.\t01, 02, ..., 12\n "
    "%-m\tMonth as a decimal number.\t1, 2, ..., 12\n "
    "%y\tYear without century as a zero-padded decimal number.\t00, 01, ..., 99\n "
    "%-y\tYear without century as a decimal number.\t0, 1, ..., 99\n "
    "%Y\tYear with century as a decimal number.\t2013, 2019 etc.\n "
    "%H\tHour (24-hour clock) as a zero-padded decimal number.\t00, 01, ..., 23\n "
    "%-H\tHour (24-hour clock) as a decimal number.\t0, 1, ..., 23\n "
    "%I\tHour (12-hour clock) as a zero-padded decimal number.\t01, 02, ..., 12\n "
    "%-I\tHour (12-hour clock) as a decimal number.\t1, 2, ... 12\n "
    "%p\tLocale’s AM or PM.\tAM, PM\n "
    "%M\tMinute as a zero-padded decimal number.\t00, 01, ..., 59\n "
    "%-M\tMinute as a decimal number.\t0, 1, ..., 59\n "
    "%S\tSecond as a zero-padded decimal number.\t00, 01, ..., 59\n "
    "%-S\tSecond as a decimal number.\t0, 1, ..., 59\n "
    "%f\tMicrosecond as a decimal number, zero-padded on the left.\t000000 - 999999\n "
    "%z\tUTC offset in the form +HHMM or -HHMM.\t\n "
    "%Z\tTime zone name.\t\n "
    "%j\tDay of the year as a zero-padded decimal number.\t001, 002, ..., 366\n "
    "%-j\tDay of the year as a decimal number.\t1, 2, ..., 366\n "
    "%U\tWeek number of the year (Sunday as the first day of the week). \n "
    "%W\tWeek number of the year (Monday as the first day of the week). \n "
    "%c\tLocale’s appropriate date and time representation.\tMon Sep 30 07:06:05 2013\n "
    "%x\tLocale’s appropriate date representation.\t09/30/13\n "
    "%X\tLocale’s appropriate time representation.\t07:06:05\n "
    "%%\tA literal '%' character.\t%\n"
)
